before_script:
    - python3.5 -m venv buildenv
    - source buildenv/bin/activate
    - pip install -v -r requirements.txt

test:
  script:
    - ./build.sh -v --debug
    - python tools/featuretest.py -g source/GlyphOrderAndAliasDB.txt test/test.json build/ScopeOne_Rg.ttf
    - scp -r build evergreen:/mnt/RAID/gitlab-builds/ScopeOne-$(git rev-parse --short=7 HEAD)/
